version: '2'
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data

  lita:
    build:
      context: .
      args:
        LITA_ENV: development
    volumes:
      - ./:/app
    ports:
      - "3000:80"
    environment:
      - "LITA_ENV=development"
      - "REDIS_HOST=redis"
    links:
      - redis:redis
