PROJECT_NAMES = [
  "Harbour Seal Matcher 3.0",
  "Bursts from Space!",
  "Decoding the Civil War",
  "Psychedelic Reports",
  "Cheetahs of Central Namibia",
  "Western Ringtail Possums: Core Habitat, Abundance, and Distribution",
  "The Old Silver of Quebec",
  "African American Civil War Soldiers",
  "Zwicky's Quirky Transients",
  "abyath",
  "Battling Birds",
  "Behind Enemy Lines",
  "Planet Four: Terrains",
  "Identifying SquidBits!",
  "Fauna Survey North East NSW with ABC North Coast Local Radio",
  "Planetary Response Network & Rescue Global: Ecuador Earthquake 2016",
  "SCOTUS Notes: Behind the Scenes at Supreme Court Conference",
  "Digital Muret",
  "Aurora Zoo",
  "Sedgwick Reserve Animal Pursuit",
  "Bristle Whistle",
  "Reaching Ithaca",
  "Seabirdwatch",
  "Slow Earthquake Hunters Alpha",
  "Serengeti Wildebeest Count",
  "Teach Robots to Read Magazines: Softalk Edition",
  "Mary Sykes Notebook",
  "Snapshot Ruaha",
  "[old] Mapping Historic Skies",
  "Let's play in the virtual world",
  "Cedar Creek: Eyes on the Wild",
  "Fossil Atmospheres",
  "Harbour Seal Matcher 2.0",
  "Galaxy Zoo: Bar Lengths",
  "Hawk Talk",
  "CHESPAX Schoolyard Biodiversity Project",
  "Describe It!",
  "The Edwardian Postcard Project (1901-1910) ",
  "Which Indian Wedding?",
  "The Rambling Microscopist",
  "Western Montana Wildlife",
  "ISTER Rowing Archive - since 1876",
  "Classrooms Around the World",
  "Conversation Starter",
  "Calgary Captured",
  "The American Soldier",
  "Galaxy Zoo - Supernova",
  "Virus Hunters",
  "Critter Snap",
  "MB07 - The Insects of the Museu Nacional de História Natural e da Ciência",
  "Galaxy Zoo",
  "Robinson Crusoe",
  "Cheese: The World's Greatest Food ",
  "Cell Hunter",
  "Unicorn Test",
  "Decoding Punch Cards",
  "Exploring Tropical Sweden",
  "Identifying and  Measuring the Urban Informal Economy and other Land Use Types",
  "Scanning Probe Microscopy Image Classification - Small Set",
  "Galaxy Zoo Workflow Tests",
  "Surgical Tool Marking",
  "Galaxy lookout",
  "Rissala Polo dream project of Colonel Ajay Ahlawat",
  "Amazo'N'Oil",
  "Mars Classification Optimization",
  "Mission To Mars",
  "lewis smelly bottom",
  "The Hunt for Galaxy Clusters",
  "iSeaU",
  "Colorado Corridors Project",
  "Planetary Response Network & Rescue Global: Caribbean Storms 2017",
  "Stripe 82 Galaxy Pairs",
  "Western Shield — Camera Watch",
  "1961 Census",
  "Focus on Wildlife -- Cleveland Metroparks",
  "Season Spotter Questions",
  "Beluga Bits",
  "Advancing AI by playing a Word Game",
  "Season Spotter Jornada",
  "Astronomy Rewind",
  "South Sudan DiversityCam",
  "Agent Alouette",
  "Finding lost towns of the Indus civilisation",
  "Solar Stormwatch II",
  "Unearthing Michigan Ecological Data",
  "Dissertation Help",
  "RAD Views",
  "Deep Lake Explorer",
  "Rainforest Flowers",
  "Macdonald Dictionary",
  "Planet Hunters TESS",
  "People Not Property: Slave Deeds Revealed",
  "AI and Magic Thumbnails",
  "Building Integrated Photovoltaics",
  "Exoplanet Explorers",
  "Cinnabar and the Geology of Dominica",
  "Science Scribbler",
  "Worlds of Wonder",
  "The Five Life Stages of Investing ",
  "Earthquake Detective",
  "Protect the last 2% of coastal Ecuador's forests",
  "AmazonCam Tambopata",
  "Camera CATalogue",
  "Penguin Watch Pro!",
  "Manuscript Madness ",
  "Notes from Nature I",
  "Snapshot Somkhanda",
  "Polar Pollinators",
  "Weather Rescue",
  "Титан Гель для мужчин Оригинал",
  "Whaling Ship Newport Logs",
  "Transcription Project",
  "Zinc deficiency induces apoptosis via mitochondrial p53- and caspase-dependent pathways in human neuronal precursor cells",
  "Mapping Historic Skies",
  "VVV proper motion search",
  "SuperWASP Variable Stars",
  "Wildebeest Watch",
  "Wild Wolf Watch",
  "Muon Hunter",
  "Planet Finders",
  "Gravity Spy",
  "Book Annotation Classification",
  "Microscopy Masters",
  "TreeVersity",
  "I Love Your Funny Face! ",
  "Parasite Safari",
  "Drop Bear Trackr",
  "Chicago Wildlife Watch",
  "Orangutan Nest Watch",
  "Discover the World",
  "Green and Grey",
  "HSC Comet Hunters Prototype",
  "Invader ID",
  "League of Nations in the Digital Age",
  "Sounds of New York City (SONYC)",
  "BLAME IT ON THE BARNACLES",
  "Plant Letters",
  "The Plastic Tide",
  "Snapshots at Sea",
  "Mapping Change",
  "Steller Watch",
  "The Bank of England as Lender of Last Resort: New Historical Evidence from Daily Transactional Data",
  "SAGA satellite zoo",
  "Wildlife Waterholes",
  "Planet Four: Ridges",
  "Contemporary Murals of Ukraine",
  "SquirrelMapper",
  "WildCam Gorongosa",
  "Snapshot Hoge Veluwe",
  "Scanning Probe Microscopy Image Classification",
  "Fishing for Drugs for Heart Disease",
  "Supernova Sighting",
  "Muon Hunters 2.0",
  "Stop the Violence, Spot the Weapon",
  "Radio Meteor Zoo",
  "Notes from Nature",
  "Astro-Ecology",
  "Untitled project 2015-07-22T14:08:23.658Z",
  "Etch a Cell",
  "Wildlife of Los Angeles",
  "Gravity Generator",
  "Lake Effect Lookout",
  "Are we alone in the Zooniverse?",
  "Comet Hunters",
  "Crowdsourcing for Rangeland Vegetation",
  "Backyard Worlds: Planet 9",
  "Euclid - Challenge the Machines",
  "Memory box",
  "Cyber Security Services",
  "ICEC-II (ice-cee)",
  "European Cinema Audiences",
  "LIFE Vison, save the critically endangered European mink",
  "Key West Court Case Transcriptions",
  "Mapping Prejudice ",
  "Milky Way Project",
  "Plecker Research",
  "Black Hole Zoo",
  "OceanEYEs",
  "Botswana Wildlife Watch",
  "Manakin Identification",
  "Penguin Watch",
  "PRN: Indonesia 2018",
  "Shakespeare's World",
  "Google Trends data Extraction",
  "Lakeside Dark Data",
  "Snapshot Supernova",
  "Galaxy Zoo in Astronomy 101",
  "Radio Galaxy ZooGems",
  "Projeto Onças do Iguaçu",
  "Guiana Gold Mining Watch",
  "Roman London's First Voices",
  "Wombat Watch",
  "Criminal Characters",
  "Scottish wildlife",
  "Season Spotter Image Marking",
  "Brain Connections",
  "Mapping Craters on Ceres",
  "Elephant Expedition",
  "eMammal",
  "PLANETS",
  "Jungle Weather",
  "Burn Scar Mapping",
  "Local Group Cluster Search",
  "Wires and Rails",
  "supernovae@zoogle",
  "Glossary Compilation of Bhutanese Archetecture",
  "London Bird Records",
  "Alternative Snapshots At Sea",
  "Annotation Tool",
  "ChildFrinendship",
  "Seafloor Explorer",
  "Check 3C vs 2C fits",
  "How do you understand colours",
  "NSW Scout Camera Photos",
  "Snapshot Grumeti",
  "Theory of Realms",
  "Cloudy with a Chance of Pain",
  "Manatee Chat ",
  "PELIcams",
  "Splitting Cells ",
  "Wildwatch Kenya",
  "Prowling with Calipers",
  "Me",
  "Ancient Lives",
  "Power of the People - Firefighter Edition",
  "Untitled project (10/07/2017, 16:24:59)",
  " Site for Sori",
  "Componente principales de los cuerpos  y microorganismo del UNIVERSO",
  "wheatstruc",
  "Describing the Archive",
  "All Bank of America Chicago Marathon results",
  "Surgical Tool Annotation",
  "With ... from Istanbul!",
  "Aztec Manuscripts",
  " Dzimbahwe Digital Archive",
  "Crocodile",
  "Fisheries Health in Cambodia",
  "Galaxy Builder",
  "Manage Your Palace ",
  "Effect of Biofield Treatment on Physical, Thermal, and Spectral Properties of SFRE 199-1 Mammalian Cell Culture Medium",
  "Hidden Killer Detective",
  "Wikiscripta Neerlandica II",
  "A Drone's Eye View on Sharks",
  "Monkey Health Explorer",
  "The Community Seagrass Initiative - Seagrass Explorer",
  "Snow Spotter",
  "Southern Weather Discovery",
  "Signal Quality Assessment for Wearable ECG 穿戴式心电质量评估",
  "Where are my body organs? ",
  "Measuring Bottlenose Dolphins 2.0",
  "changing ladakhi traditional architecture",
  "Junior Coders",
  "Mile-a-minute Weed",
  "Poppin' Galaxy",
  "Archives Départementale de l'ALLIER ",
  "Fossil Finder",
  "DCWStyleMarkingOptions",
  "Wild Basin Wilderness Preserve",
  "Supernova Hunters",
  "Candid Emiquon",
  "Farmers Diabetes (3/8/2018, 4:34:11 PM)",
  "Solar Windsocks ",
  "Galaxy Zoo Mobile",
  "!Identify your city!",
  "The Magellanic Clouds Project",
  "Humpbacks and High-Rises",
  "Kit’s Towing",
  "Ngā manu tātākī",
  "Black Hole Wind Watch",
  "Aerial wildlife surveys in Africa",
  "Medieval Illumination",
  "Plankton Portal",
  "Dark Universe Welcome",
  "Snapshot Serengeti",
  "Space Warps",
  "HETDEX",
  "Spiral Graph",
  "Agent NEO",
  "Planetary Response Network",
  "Scribes of the Cairo Geniza",
  "Szabadság tér",
  "classifying ant's ",
  "Rediscovering Oral History",
  "Project Soothe",
  "What Is That? (4/3/2017, 3:50:51 PM)",
  "Pipo adventures",
  "Classifying Invertebrates and Birds",
  "Protect Our Planet From Solar Storms",
  "Eagle Zoo",
  "Digital Crowdsourcing for Rangeland Vegetation",
  "Untitled project 2015-12-30T18:10:51.482Z",
  "Retail Experiences ",
  "Outer Limit: XUV-disks",
  "Galaxy Zoo: 3D",
  "Best Fertility & IVF Treatment centre",
  "Interior Least Tern and Piping Plover Predators",
  "Oz Assignment help",
  "Snapshot Wisconsin",
  "Intro2Astro: Hubble's Law",
  "Flow Finder: Arizona Water Watch",
  "Canid Camera",
  "Looking at Logos",
  "Rodent Little Brother: Secret Lives of Mice",
  "Asteroid Zoo",
  "Natural History and Chinese Painting",
  "ZTF_Class",
  "Identifying Cyberbullying: What would you do about it?",
  "Fuel Cell Plane",
  "Herbaria for science",
  ":poop:",
  "Penguin Watch MPLS",
  "Solar Stormwatch II",
  "Wisconsin Wildlife Watch",
  "Exeter Test Transcription Project",
  "Count flowers for bees",
  "Snapshot Mariri",
  "Toledo Zoo Wild Shots",
  "playing around",
  "Twitter Emotions",
  "Santa's DH helpers",
  "Human age",
  "Mount Vernon Graffiti",
  "AnnoTate",
  "Send In The Clones",
  "micro orquídeas sp do Brasil",
  "HRMAn: Colourful Pathogens",
  "Mars in Motion MSSL",
  "Solar Flare",
  "Mars in Motion",
  "Michigan ZoomIN",
  "Monument-buildings of Yerevan",
  "Centaur Heaven",
  "Floating Forests v1",
  "eMammal",
  "Galactic Archaeology",
  "Cosmos IRAC galaxy pairs",
  "ALGERIANBAT GROUP - PROJECT",
  "Traffic analytics project",
  "Пробный проект",
  "Flora Latinoamericana",
  "Games that make games 'GameLab'",
  "Crowd sourced analysis of tissue slides for the identification of cancerous cells - a gaming approach",
  "Test",
  "Microplants",
  "Galaxy Identification",
  "Kitteh Zoo",
  "Spiral Spotter",
  "Penguin Watch YSJ",
  "Art in Miniature - Original",
  "Unicorns",
  "Plant Letters (from Africa)",
  "African music through a lens!",
  "Clay solar system",
  "DESY3-XCS (PSF's classification)",
  "Bright Stars (8/15/2017, 8:43:56 PM)",
  "Kitteh Zoo2",
  "TEST PROJECT",
  "OrgStatsTest1",
  "Unicorn_2",
  "The Bottlenose Dolphin Project delete",
  "Harbour seal photo-ID project",
  "Untitled project (3/26/2018, 11:33:14 AM)",
  "Test Project for Planet Labs Stuff",
  "PINKERE",
  "Landscape Watch",
  "Test Project",
  "WWI History Questionnaires",
  "nest watch",
  "Weddell Seal Count",
  "Zoominar",
  "CERN@school: Particle ID 101",
  "Notes from Nature classification testing",
  "CPPMemex",
  "NAM Galaxy Zoo",
  "Jelleh Zoo",
  "ECOLIT",
  "New Planets",
  "The Plastic Tide - TPT",
  "Test No Subjects Beta",
  "james-artz-test",
  "Untitled project (7/26/2017, 2:48:06 PM)",
  "Austin Wildlife Watch",
  "Variable Star Zoo",
  "Miniature Lives Magnified",
  "Golan Wildlife",
  "Megamovie Maestros I",
  "Old Lviv",
  "Aye Aye Vocalization Coding",
  "ChicagoAtNight",
  "Muffin mystery",
  "Space Warps - HSC",
  "Met Morph but not Martin's Radio Loud Criteria",
  "Astronomical Event Tracker",
  "PLZ WORK 2",
  "Find Me Some Clusters!",
  "Pennywise Cleaners",
  "Leaf Prints",
  "CS Summer School  ",
  "10/19/18",
  "Wormhole Hunters",
  "SolarEnergyMaps.com",
  "en-comics",
  "Penguin Zoo",
  "Comet or not to comet, that is the ansver",
  "Puget Sound Seabird Survey",
  "HumBug",
  "Passports",
  "Project Plumage",
  "The Lance-tailed Manakin Project",
  "Cats project",
  "Consumer Claim Line",
  "medival cats",
  "Cyclone Center - Storm Lab",
  "An Investigation of Tennessee's Invasive Plant Species",
  "The Rocket Project",
  "The Milky Way Project (Blink)",
  "Flare Identification",
  "Whatever happened to Lady Grange?",
  "HSC-SSP TNOs",
  "Words of the Alaska Governors",
  "Assignment help",
  "Offset Bar Search",
  "COSMIC",
  "Run, Herring, Run!",
  "Career In Real Estate",
  "Global warming",
  "Digital Crowdsourcing for Vegetation ",
  "planet census",
  "Whatever the Space Weather",
  "Space rock",
  "Blue Raster",
  "A People's Guide to English Usage",
  "Identify New Zealand animals",
  "Untitled project (May 19, 2017 at 3:52:57 PM CDT)",
  "HETDEX - finding distant galaxies to measure dark energy",
  "Brain Match",
  "Saving Bengal Tigers",
  "Galaxy Nurseries Original",
  "Plastic Tide",
  "WISPS Flipbook Test",
  "Weed Out Miconia",
  "AncientTextualLives",
  "Pulsar Hunters",
  "Milky Way Project",
  "King's Lynn Borough Archives",
  "Galaxy Zoo",
  "Parochial Archive Project in Rome",
  "Image Categorization",
  "Jungle Rhythms",
  "National Historic Literary Landmarks and Artifacts of the Northeast (9/26/2018, 9:15:29 PM)",
  "SongStory",
  "The OCEANIC Colonization Data Challenge",
  "Pieris Project ",
  "Arastradero  Camera Trap ",
  "Hazardous Thunderstorm Identification",
  "A study of insects",
  "Medigap Quotes",
  "Estudando o Vitral",
  "Archivo Digital Nacional de Puerto Rico -ADNPR-Pasaportes a Republica Dominicana",
  "Astronomy Rewind Education Page",
  "p",
  "Planet Hunters Round 2",
  "Importance of filing cabinets",
  "Santa or Scientist",
  "Cephalopods",
  "Gold Rush",
  "The Wilds' Wildlife Watch",
  "Kittens for AkLA",
  "Penguin Watch",
  "West Australia Glenbourne Fauna ID ",
  "HuMaIN",
  "NOAH Testing",
  "Erosão Costeira",
  "Fish interaction (10/06/2017, 9:39:04 pm)",
  "Help Monarch Butterfly Research",
  "Red Panda Behaviour",
  "Interacting Galaxies at z=0",
  "Taranaki Mounga ",
  "Slavery From Space",
  "South Bend Lead Identification Project",
  "Hubble Catalog of Variables (HCV)",
  "Project Name",
  "Zooniquiz",
  "Paired-object Systems",
  "Car Carrier",
  "Test Project",
  "Drivers and barriers",
  "Letters to Ryan",
  "MarsScout",
  "Simple Test Project",
  "TEST WW1 POW Postcard Transcription",
  "Weather Rescue Ben Nevis",
  "Galaxy Zoo - Mergers",
  "The Early Reference Project",
  "TESS",
  "FamilySearch Indexing",
  "Snapshot Wisconsin Challenge",
  "Morphological Classification of Pan-STARRS",
  "Botanists' Letters!",
  "Bat Detective",
  "Disk Detective",
  "Airline Logo",
  "Cursive Segmentation",
  "Save Streets of the Old Lviv",
  "Soils of Asteroids",
  "Adinkra Popular culture.",
  "Introduction to the Zoo Tools",
  "ZOOGEMS",
  "Lord of the Flies: Civilization vs. Savagery",
  "en-dissimilitudes",
  "Need of hiring electrical contractors NJ",
  "Marginaliotate",
  "Motivation Survey for Crowdsourcing Platform User (Academic Use)",
  "Numbat Discovery",
  "DeepRoot",
  "Deepwater Horizon: Oil or not?",
  "Letter from Poland",
  "Comunicación cotidiana como dificultador del aprendizaje de ciencia y tecnología.",
  "Zubaran",
  "NuKhemical Cat",
  "Measuring the ANZACs",
  "HEALTH-I",
  "Worm Watch Lab",
  "AP AAS231 Test",
  "Pluto Crater Detective",
  "Why Did the Wildlife Cross the Road?",
  "Project Gaia",
  "A World High Above: Birds",
  "Scribes of the Cairo Geniza Phase 2 Workflow Testing",
  "Leaf Targeting",
  "Fragment Pairs",
  "Animal Videos",
  "oldWeather OCR",
  "Dinosaur Teeth",
  "Transcribing the Caribbean",
  "THEORY- INTERN HUMAN SYSTEM KINETIC ENERGY COULD BE TRANSPORTED  (2016-10-12 14:32:42)",
  "Lift the secret of sloth cuteness!",
  "Australian Safari",
  "Galaxy Nurseries",
  "Most adorable pets",
  "COASST Debris ",
  "Chicago Wildlife Watch Original",
  "PlayStation plus 365 tage kaufen",
  "Project Apollo Stories",
  "AMT_proj_06",
  "Panoptes shapes",
  "Hampshire Landscape Watch",
  "Mammalogy 2018",
  "Street Quality Identification Device",
  "GALAXY PAIRS 101",
  "Kitteh Zoo1",
  "Winter Human Health",
  "Pigments",
  "This should be changed sho",
  "Floods of the Past",
  "Census Clicker",
  "Game of Fashions",
  "Reading Nature's Library",
  "Kilonova Quest",
  "Icarus Investigations",
  "X-Ray Lab",
  "Hubble's Hot Stars",
  "Roll The Credits",
  "canna if I juanna",
  "Brazil, Rio de Janeiro, Obituaries, 1998",
  "CLASH UdeC",
  "Flud",
  "Animal, Vegetable, Mineral",
  "Comparaisons",
  "Classifying Simulated Galaxies",
  "Galaxy Zoo Demo July 2018",
  "Homeless Animals",
  "Wayne State Workshop Project",
  "À la Carte",
  "Untitled project (5/10/2016, 4:22:18 PM)",
  "Digging the Potomac",
  "Text test",
  "Benefits Of Online Gaming",
  "The Anomaly",
  "Security Tests",
  "Sketchley Valley pedestrian survey",
  "Space Civilization  with the ALIENS ",
  "Seismic Events",
  "Freehand Tools Test",
  "Count the fish",
  "North Country Wild",
  "testapp",
  "Stellar Autopsies",
  "BarBulge",
  "cats",
  "Life of diaspora",
  "Utah Wildlife",
  "Heating Service NJ",
  "Finding Feral Cats A Home",
  "Tidal Remnants Around Low Excitation Radio Galaxies",
  "The Ronald M. and Dianne J. Bernier Archive",
  "Digitizing Industrial Heritage",
  "Andromeda Project",
  "Discover Exploding Stars (04/03/2017, 3:52:32 pm)",
  "Measuring Bottlenose Dolphins 1.0",
  "Material Science And NanoPhysics Discsussion Project (4/23/2018, 7:46:40 AM)",
  "Carlisle Health Highlights (Beta)",
  "Galaxy Zoo: Clump Scout!",
  "Galaxy classification",
  "Building Location Finder",
  "My Backyard",
  "Gotham Coyote",
  "Mars or Earth?",
  "Codex Aubin for HILT",
  "test",
  "oldweather",
  "Enchanted Manuscripts",
  "Elephants and Bees - Camera watch",
  "My Project",
  "Understanding Animal Faces",
  "Orchid Observers",
  "Symmetry of Supernova Remnants",
  "Nebraska Wildlife Watch ",
  "NikolayTest (09.01.2018, 12:53:18)",
  "An Untitled project",
  "Our Country Lives",
  "Urban Monitoring",
  "EOT Metadata Prototype",
  "NEEMO",
  "Mirabilia Urbis Romae",
  "Texting the Caribbean",
  "Snapshot APNR",
  "Who's been sleeping in my burrow?! ",
  "Untitled project 2016-01-29T20:42:45.795Z",
  "Season Spotter Sandbox",
  "Test",
  "Grouse Grooves",
  "Translate Classics",
  "COSMIC WHEEL .",
  "Galaxy Zoo for Schools Outreach",
  "You know Food?",
  "Bar Finder",
  "The Old Lviv Street View",
  "ZTF_RB_Project",
  "Faces of the World",
  "River debris detection",
  "Eagle Zoo old unused",
  "Centaur Heaven - hp5",
  "Sigurd Bruhns ægsamling",
  "NfN Badge Testing",
  "TreeLeave",
  "Wildlife at Oxy",
  "Markdown Practice",
  "Higgs Hunters",
  "Flexing Mussels: Environmental Change In Wisconsin Over 100 Years",
  "Faces Demo",
  "GZ2Redo--Take2!",
  "B/P Bulge Finder",
  "help me find roblox stuff and fortnite locations and weapons NOW help????????????",
  "Video Clip Upload Site",
  "Maps on Stamps",
  "Blast from the Past!",
  "Discover Denmark",
  "Camera trap sequences: test your species ID skills",
  "SQUID-Bike-NYC",
  "HSC Supernova Hunting",
  "Mutual Muses",
  "Broken Extended Sources",
  "Tunning Standard Quest",
  "Anti-Slavery Manuscripts",
  "Planet 9",
  "Maize Height",
  " iCert Global | Live Online and Classroom Certification Training>",
  "Science Gossip",
  "Epithelial Identification",
  "Field of Vision",
  "ZTF Public (MSIP) Project",
  "GTA Party Bus",
  "Recipe Cards",
  "test_feedback",
  "Floating Forests",
  "memes",
  "toilet paper debate",
  "Untitled project (5/8/2018, 4:21:11 PM)",
  "Galaxy Zoo: star or wrong sized image of galaxy?",
  "Cells",
  "PLZ WORK",
  " Pohutukawa myrtle rust disease ",
  "Exploring Our Extra-Galactic Backyard",
  "Eye for Diabetes",
  "Cluster Zoo",
  "Leaves and Tassels",
  "PHT - Candidate Test ",
  "OrgStatsTest3",
  "NovelMapper",
  "FamilySearch Boundary Test",
  "Planet Hunters",
  "Coding Metaphors, Similes, & Idioms in Writing Tasks",
  "Microplants",
  "Monopole Quest!",
  "Stickleback Birdwatch",
  "Plankton Portal Relaunch",
  "The Horse Call",
  "Active Weather",
  "OSSOS light curve review",
  "Vintage Galaxy Zoo",
  "76",
  "How many Jaguars are there?",
  "Science Projects",
  "Demo",
  "Galaxy Zoo at NAM",
  "Rapid adaptation to environmental change in stickleback",
  "Riveredge Burrow Project",
  "Deforestation",
  "BH' Albania",
  "CSH Project",
  "Biofield",
  "Dietonus (Диетонус) капсулы для похудения",
  "Change Minds",
  "Occhio alle Penne!",
  " astronomie 9 7 4 découverte de l'univers",
  "AAS galaxies",
  "Trash On The Beach",
  "Literature On The Black Soldier Fly (Hermetia Illucens) ",
  "Protein Picker",
  "Pattern Perception",
  "Leaves and Tassels",
  "Imagining the future (7/4/2016, 2:42:24 PM)",
  "Classification mission!",
  "Flying HI",
  "Cave Hopper",
  "Met Morph and Martin Radio Loud Criteria",
  "Measuring Bottlenose Dolphins 3.0",
  "SETI Live",
  "Census",
  "Sugar, flower, fish or gravel",
  "Demo",
  "CSH word images",
  "AMT_proj_01",
  "InkSpotter (Ben)",
  "AMT_proj_02",
  "save the chickens",
  "LetsLyrics",
  "Monitore Tupinambás",
  "College Radio Archive",
  "Whales as Individuals",
  "Loray Digital Archive",
  "Cyclone Center: Eye of the Storm",
  "Polyglot",
  "Test Project MB",
  "MaNGA Kinematic Classification",
  "Generate panicles training data",
  "How angry is Gordon Ramsay?",
  "Coral growth",
  "Fonds Robichon",
  "Soviet mosaics in Lviv",
  "AMT_proj_00",
  "Decoding The Civil War Phase 2 ",
  "Planet Four",
  "Michigan's Unique Animal Family ",
  "Transcribing Mixtec",
  "Condor Watch",
  "GStest",
  "Mars in Motion v3",
  "Philadelphia Playbills Project",
  "Nose freckles ",
  "Season Spotter BASIC Beta1",
  "MOCK: Planetary Response Network 2019-2020: Fallout Mapper",
  "Planet Finders: TESS",
  "Null PSF's classification",
  "Rocky Mountain National Park - Wildlife Identification",
  "&& -- black holes -- ;;",
  "Reclaiming Nzulezu",
  "WildCam Darién",
  "Seal Counter",
  "Season Spotter DETAILS Beta1",
  "Image Tagging",
  "Astronomy observing & viewing",
  "Événements 1837-1838",
  "Concord or Concorde?",
  "FFTutorial",
  "Steelpan Vibrations",
  "PageFreezer Diffs",
  "Revenge of the Kittehz (Grant is Awesome)",
  "Family certificates",
  "What's The Score",
  "Tagging the Natural World",
  "Kitten Zoo  🐱🐱🐱",
  "Ice Hunters",
  "K2: Background Survey",
  "AMT_proj_03",
  "Galaxy Test",
  "Team CPT: Beamline 4 Schools",
  "Ancient Lives Ouroboros",
  "Family certificates St-Brieuc",
  "Bash the Bug",
  "Does house shape matter?",
  "Street Quality Identification Device - SYR",
  "testing",
  "AMT_proj_07",
  "Table Test",
  "Nuclear disc search",
  "cats",
  "DES Internal GP",
  "fr-dissimilitudes",
  "Maize Leaf Count",
  "Jean-Louis Bagot",
  "Why to choose memory care Morris NJ?",
  "Test Project",
  "Newspaper Advertisements of Interwar Lviv",
  "AMT_proj_05",
  "Sleep Scoring",
  "friday project",
  "Virus inhibiting effects of meal worm poop",
  "Planet Hunters Protoype",
  "Drawing tools test",
  "fixithere",
  "Rain Drop on Plants ",
  "Tree Watch",
  "Kauri Dieback Disease",
  "Radio Galaxy Zoo",
  "identifying New Zealand native birds",
  "Candels f160w",
  "Diagnosis London",
  "Sierra Nevada Mammal Madness ",
  "Flora of the East Coast (New England)",
  "Koala ocular disease",
  "Protecting the French border",
  "Blue Sky",
  "Cell Slider",
  "wave watcher",
  "Demo for Identifying Ultra Diffuse Galaxies",
  "CrowdCount",
  "Stardate M83",
  "Test-project",
  "Harbour Seal Matcher 1.0",
  "AMT_proj_09",
  "AMT_proj_08",
  "Galaxy Generation",
  "Dog project (11/27/2017, 11:17:55 AM)",
  "without file",
  "MaStar Quality Visual Inspection",
  "The Naturalist's Scrapbook",
  "Star Party!",
  "Computer Vision: Serengeti",
  "DEVELOPMENTAL IDEAS",
  "Blavatnik-McGill Test Project",
  "PotHoles",
  "La Linterna",
  "Pick all the bugs",
  "Rain twitter",
  "Slavery from Space - Dev",
  "The Solar System",
  "Prettiest Pugs",
  "Operation War Diary",
  "Saving the Bees",
  "Sorting Spectra",
  "Stellar Sleuths",
  "Libcards",
  "Chimp & See",
  "Diabeteens",
  "Stellar Haloes",
  "Star Trek Aliens",
  "Brazil, Rio de Janeiro,Imigração Postais",
  "Building The T.A.R.D.I.S",
  "Detection of Supernovae",
  "Whale FM",
  "Wildlife threats",
  "Conifers",
  "Projet exo",
  "PDA WATCH 1",
  "The Personality Of Spotify Users",
  "Arizona BatWatch",
  "Danish Butterflies and Moths 2020 Challenge",
  "The Jaguar's Jungle",
  "Kapasan",
  "Drain cleaning service NJ",
  "LSST Zoo (Test)",
  "Untitled project (3/31/2017, 5:18:58 PM)",
  "Somalia deforestation watch",
  "Lego Parts",
  "Cloud classification test",
  "LSST Example Project",
  "Poppin' Candy",
  "OrgStatsTest2",
  "Jewish necropolis",
  "UMBS Mustelid Habitat Suitability (UMHS) Project",
  "Pottery Classification",
  "Surveillance online ",
  "Test functionality",
  "Planet Four",
  "Twinkle",
  "ZooCon 2015",
  "Kilmer or Russell?",
  "Vehicular Art Project",
  "Kitteh Zoo",
  "Top Sunglasses adding vibe to your summer look",
  "Cosmic Web",
  "MaNGA Quality Control Inspection",
  "Pasos Modernos",
  "#vaccine",
  "MarineGeo",
  "Online Wisdom Lab",
  "Snapshot Serengeti Ouroboros",
  "Moon Crater Lab",
  "Fruit & Veggie Identification",
  "Finding more about the Big Bang",
  "Watch power Season 4 Episode 7 Online Free Putlocker",
  "Retinal disease detection",
  "Seribu Nama Sirih (2017. 06. 06. 15:52:05)",
  "Untitled project (7/4/2018, 5:55:37 PM)",
  "Earthworm Invasions! Classifying Historical Land Uses",
  "Galaxy Bars",
  "Archive_Site 4 Sori",
  "Ferengi Galaxies",
  "Kitten Zoo",
  "testing tutorial",
  "Words",
  "TestProject",
  "Make Green",
  "Social media project",
  "FERENGI Stage 1 ",
  "Cat Project",
  "TobyTest",
  "Invasive Plants 101",
  "A. Hua AR378 Practice",
  "Handwritten Digits",
  "/b/",
  "My Project",
  "Upload Test",
  "We're Still Here!",
  "Manuscript Adventure",
  "CameraTrapTest",
  "Getting Texty",
  "Donald Trump (‎17‎/‎08‎/‎2017‎ ‎15‎:‎44‎:‎55)",
  "Old Weather",
  "Traffic Cams - ORNL",
  "Solar Stormwatch",
  "Rekognition test",
  "Digital Skies",
  "Dion island emperors",
  "Find the Clusters!",
  "Meme or Paining? (7/10/2018, 1:55:31 PM)",
  "State Silk Museum Collection",
  "Pembroke 400 test",
  "GAMA Zoo",
  "Let's learn about the Solar System an classify trees.",
  "Cats project",
  "Leaf Region",
  "What's in the box? (19.7.2017, 13:23:46)",
  "HUDS",
  "test",
  "LOTS OF CATS",
  "Dog's Life Project",
  "Microplants",
  "Demo Project: Astro",
  "The Buchanan Notebook",
  "March of Signs",
  "Fragmental thinking",
  "IRIS STEM Image Descriptions",
  "full hd image of earth",
  "Expert Smooth/Not",
  "Urbarium 1767",
  "CT Copyright Records Test",
  "تقييم الكتاب المدرسي - المغرب",
  "zooniverse tutorial at lsst data viz workshop",
  "AMT_proj_04",
  "Les registres matricules",
  "Wildcam Gorgonzola",
  "Slavery From Space: Punjab",
  "Rights Lab: Slavery From Space",
  "Project",
  "Box Turtle Survey (8/2/2016, 12:19:36 PM)",
  "what type of breed of dog is it",
  "Knowing Malevich",
  "GAIA Alerts",
  "Death certificate transcription",
  "Is This a Statue?",
  "Is this a galaxy?",
  "ol",
  "Emigrant City",
  "Is it good?",
  "BEARDED DRAGON",
  "Private Particle Detective",
  "duplicate-test",
  "Mites and Lice in birds.",
  "Galaxy Zoo bar lengths",
  "XD",
  "My Testing project",
  "Fish Annotation",
  "Cyclone Center",
  "park",
  "Cat next top model ",
  "Pokemoth Go",
  "Untitled project (11/20/2018, 11:27:22 AM)",
  "Is that an alien?",
  "CamCat-Empty",
  "Help eliminate speeding tickets.",
  "Just a test - Duke Papyri",
  "Pollution and waste management ",
  "Sachtleben Diaries",
  "Ducks (20/06/2016, 13:57:37)",
  "Sunspotter",
  "Moon Zoo",
  "666 Plz help dem",
  "Penguin Spotter #2",
  "X marks the spot",
  "Dummy project",
  "Artefact Hunter",
  "Zen of Dragons",
  "Understanding image quality ",
  "Gravity Spy - 222 Seismic",
  "ADACS Galaxy Classification",
  "Near-Earth Asteroid Detection",
  "Health control of ships",
  "Research Classification",
  "Ecuador Demo LOLZ"
]
